name: share_h
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  velocity_x: ^3.6.0
  flutter_launcher_icons: ^0.10.0
  device_info_plus: ^8.0.0
  nearby_connections: ^3.2.0
  ripple_animation: ^0.0.1+2
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  sqflite: ^2.2.2
  file_picker: ^5.2.4
  flutter_share: ^2.0.0
  shared_preferences: ^2.0.15
  fluentui_system_icons: ^1.1.190
  path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/applogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/avatar/
    - assets/icon/
    - assets/history_empty_view/
